import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

function load(rel) {
  return JSON.parse(readFileSync(join(root, rel), "utf8"));
}

const payloadDir = join(root, "schemas", "payloads");
const responseDir = join(root, "schemas", "responses");
const payloads = {};
for (const name of readdirSync(payloadDir)) {
  if (!name.endsWith(".json")) continue;
  payloads[name.replace(/\.json$/, "")] = load(`schemas/payloads/${name}`);
}
const responses = {};
for (const name of readdirSync(responseDir)) {
  if (!name.endsWith(".json")) continue;
  responses[name.replace(/\.json$/, "")] = load(`schemas/responses/${name}`);
}

const data = {
  rules: load("rules.json"),
  envelope: load("schemas/request-envelope.json"),
  response: load("schemas/response-envelope.json"),
  payloads,
  responses,
};

const out = `/* generated by embed-schemas.mjs — do not edit by hand */\nexport const SCHEMA_DATA = ${JSON.stringify(data, null, 2)};\n`;
writeFileSync(join(root, "js", "schema-data.mjs"), out);
console.log("wrote js/schema-data.mjs");
