// Emits js/protocol.d.ts from the D05 schemas.
//
// The messageType -> schema mapping is NOT restated here. It is read back out of
// schema-lite.mjs at generation time and matched by $id, because that mapping is
// irregular in two places a filename convention cannot express:
// `application.queryCandidates` -> query-candidates, and job.save / fill.submit /
// submit.confirm all sharing the single `write` response. Restating it would create
// exactly the second source of truth the vendored-validator design avoids.
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join, basename, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { envelopeSchema, responseSchema, payloadSchema, responsePayloadSchema } from "./schema-lite.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const NL = "\n";

function pascal(name) {
  return name.split(/[-_.]/).filter(Boolean).map((part) => part[0].toUpperCase() + part.slice(1)).join("");
}

// Interface name for a schema, keyed by its $id so a caller can look one up from the
// schema object alone.
function interfaceName(id) {
  const file = basename(id, ".json");
  if (file === "request-envelope") return "RequestEnvelope";
  if (file === "response-envelope") return "ResponseEnvelope";
  if (id.includes("/responses/")) return `${pascal(file)}ResponsePayload`;
  return `${pascal(file)}Payload`;
}

// Constraints do not survive into the type system, so carry the ones a caller would
// otherwise have to open the schema to find.
function constraintDoc(schema) {
  const notes = [];
  if (schema.pattern) notes.push(`pattern: ${schema.pattern}`);
  if (schema.minLength !== undefined) notes.push(`minLength: ${schema.minLength}`);
  if (schema.maxLength !== undefined) notes.push(`maxLength: ${schema.maxLength}`);
  if (schema.minimum !== undefined) notes.push(`minimum: ${schema.minimum}`);
  if (schema.maximum !== undefined) notes.push(`maximum: ${schema.maximum}`);
  if (schema.minItems !== undefined) notes.push(`minItems: ${schema.minItems}`);
  if (schema.maxItems !== undefined) notes.push(`maxItems: ${schema.maxItems}`);
  if (schema.description) notes.unshift(schema.description);
  return notes;
}

function typeExpr(schema, indent) {
  if (Array.isArray(schema.enum)) return schema.enum.map((v) => JSON.stringify(v)).join(" | ");
  switch (schema.type) {
    case "string": return "string";
    case "boolean": return "boolean";
    case "integer":
    case "number": return "number";
    case "array": return `${typeExpr(schema.items ?? {}, indent)}[]`;
    case "object": return schema.properties ? objectBody(schema, indent) : "Record<string, unknown>";
    default: return "unknown";
  }
}

function objectBody(schema, indent) {
  const pad = " ".repeat(indent + 2);
  const required = new Set(schema.required ?? []);
  const lines = ["{"];
  for (const [key, value] of Object.entries(schema.properties)) {
    const notes = constraintDoc(value);
    if (notes.length === 1) lines.push(`${pad}/** ${notes[0]} */`);
    else if (notes.length > 1) lines.push(`${pad}/**`, ...notes.map((n) => `${pad} * ${n}`), `${pad} */`);
    lines.push(`${pad}${key}${required.has(key) ? "" : "?"}: ${typeExpr(value, indent + 2)};`);
  }
  lines.push(`${" ".repeat(indent)}}`);
  return lines.join(NL);
}

function declare(schema) {
  const name = interfaceName(schema.$id);
  const title = schema.title ? `/** ${schema.title} */${NL}` : "";
  return `${title}export interface ${name} ${objectBody(schema, 0)}${NL}`;
}

const load = (rel) => JSON.parse(readFileSync(join(root, rel), "utf8"));
const collect = (dir) =>
  readdirSync(join(root, "schemas", dir))
    .filter((n) => n.endsWith(".json"))
    .sort()
    .map((n) => load(`schemas/${dir}/${n}`));

const mapEntries = (rows) =>
  rows.map(([type, schema]) => `  ${JSON.stringify(type)}: ${interfaceName(schema.$id)};`).join(NL);

/** Render protocol.d.ts from the schemas on disk. Pure: writes nothing. */
export function renderTypes() {
  const envelope = envelopeSchema();
  const response = responseSchema();
  const payloads = collect("payloads");
  const responses = collect("responses");
  const messageTypes = envelope.properties.messageType.enum;

  // Resolve each messageType through the real runtime mapping rather than a copy of it.
  const requestRows = messageTypes.map((t) => [t, payloadSchema(t)]);
  const responseRows = messageTypes.map((t) => [t, responsePayloadSchema(t)]);
  for (const [type, schema] of [...requestRows, ...responseRows]) {
    if (!schema) throw new Error(`schema-lite.mjs has no schema for messageType ${type}`);
  }

  return `/* generated by gen-types.mjs — do not edit by hand */
/* Source of truth: desktop/crates/protocol/schemas/. Regenerate with:
   node desktop/crates/protocol/js/gen-types.mjs */

export type MessageType =
${messageTypes.map((t) => `  | ${JSON.stringify(t)}`).join(NL)};

${[envelope, response, ...payloads, ...responses].map(declare).join(NL)}
/** Request payload type for a given messageType. */
export interface RequestPayloadByType {
${mapEntries(requestRows)}
}

/** Response payload type for a given messageType. Several writes share one response. */
export interface ResponsePayloadByType {
${mapEntries(responseRows)}
}

/** One request envelope, narrowed to the payload its messageType carries. */
export type RequestFor<T extends MessageType> = Omit<RequestEnvelope, "messageType" | "payload"> & {
  messageType: T;
  payload: RequestPayloadByType[T];
};

/** A successful response, narrowed to the payload the request's messageType expects. */
export type ResponseFor<T extends MessageType> = Omit<ResponseEnvelope, "payload"> & {
  ok: true;
  payload: ResponsePayloadByType[T];
};
`;
}

export const OUTPUT_PATH = join(here, "protocol.d.ts");

const isMain =
  Boolean(process.argv[1]) &&
  resolve(fileURLToPath(import.meta.url)) === resolve(process.argv[1]);
if (isMain) {
  writeFileSync(OUTPUT_PATH, renderTypes());
  console.log("wrote js/protocol.d.ts");
}
